In [3]:
import numpy as np

# 입력 데이터와 목표값
X = np.array([[0, 0], [0, 0.5], [0, 1], [0.5, 0.5], [0.5, 1], [1, 0], [1, 0.5], [1, 1]])
y = np.array([1, 1, 1, 2, 1, 1, 1, 1])
# 다층 퍼셉트론의 가중치와 편향 초기화
w1 = np.random.randn(2, 3)
b1 = np.random.randn(3)
w2 = np.random.randn(3, 1)
b2 = np.random.randn(1)
# 하이퍼파라미터 설정
learning_rate = 0.1
epochs = 1000
# 경사 하강법으로 다층 퍼셉트론 학습
for epoch in range(epochs):
    # 순전파
    z1 = np.dot(X, w1) + b1
    a1 = 1 / (1 + np.exp(-z1))
    z2 = np.dot(a1, w2) + b2
    a2 = 1 / (1 + np.exp(-z2))

    # 오차 계산
    error = y.reshape(-1, 1) - a2

    # 역전파
    delta2 = error * a2 * (1 - a2)
    delta1 = np.dot(delta2, w2.T) * a1 * (1 - a1)

    # 가중치와 편향 업데이트
    w2 += learning_rate * np.dot(a1.T, delta2)
    b2 += learning_rate * np.sum(delta2, axis=0)
    w1 += learning_rate * np.dot(X.T, delta1)
    b1 += learning_rate * np.sum(delta1, axis=0)

In [8]:
w1,w2

(array([[-1.82733214, -0.35235346,  2.39044244],
        [-0.9743467 ,  0.63325588, -0.15644315]]),
 array([[ 2.06063214],
        [-0.00501986],
        [ 2.69050468]]))

In [9]:
b1,b2

(array([1.69569899, 0.88379047, 0.25887894]), array([2.48208145]))

In [1]:
import numpy as np

# 입력 데이터와 목표값
X = np.array([[0, 0], [0, 0.5], [0, 1], [0.5, 0.5], [0.5, 1], [1, 0], [1, 0.5], [1, 1]])
y = np.array([1, 1, 1, 0, 1, 1, 1, 1])

# 다층 퍼셉트론의 가중치와 편향 초기화
w1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
w2 = np.random.randn(4, 3)
b2 = np.random.randn(3)
w3 = np.random.randn(3, 1)
b3 = np.random.randn(1)

# 하이퍼파라미터 설정
learning_rate = 0.1
epochs = 1000

# 경사 하강법으로 다층 퍼셉트론 학습
for epoch in range(epochs):
    # 순전파
    z1 = np.dot(X, w1) + b1
    a1 = 1 / (1 + np.exp(-z1))
    z2 = np.dot(a1, w2) + b2
    a2 = 1 / (1 + np.exp(-z2))
    z3 = np.dot(a2, w3) + b3
    a3 = 1 / (1 + np.exp(-z3))

    # 오차 계산
    error = y.reshape(-1, 1) - a3

    # 역전파
    delta3 = error * a3 * (1 - a3)
    delta2 = np.dot(delta3, w3.T) * a2 * (1 - a2)
    delta1 = np.dot(delta2, w2.T) * a1 * (1 - a1)

    # 가중치와 편향 업데이트
    w3 += learning_rate * np.dot(a2.T, delta3)
    b3 += learning_rate * np.sum(delta3, axis=0)
    w2 += learning_rate * np.dot(a1.T, delta2)
    b2 += learning_rate * np.sum(delta2, axis=0)
    w1 += learning_rate * np.dot(X.T, delta1)
    b1 += learning_rate * np.sum(delta1, axis=0)


In [2]:
print(f"weight1 = {w1} \nbias1 = {b1}")
print(f"weight2 = {w2} \nbias2 = {b2}")
print(f"weight3 = {w3} \nbias3 = {b3}")

weight1 = [[ 0.6999485  -1.08623003  1.13029644  0.12879079]
 [ 0.48979496 -0.28084263 -0.42901278  0.78394719]] 
bias1 = [-0.28140963  1.18489825  0.25356535  0.36556133]
weight2 = [[-0.81145777  0.40281582 -0.77910876]
 [-1.19294199 -1.18544343 -1.17876312]
 [ 0.87694572 -0.41137187 -0.98295595]
 [-0.09603364  1.25772578 -0.23160335]] 
bias2 = [-1.89719591 -0.25644782 -1.90635486]
weight3 = [[-0.1893349 ]
 [ 1.46910571]
 [ 0.9442457 ]] 
bias3 = [1.24372927]


In [4]:
# 다층 퍼셉트론의 가중치와 편향 초기화
w1 = np.random.randn(2, 3)
b1 = np.random.randn(3)
w2 = np.random.randn(3, 1)
b2 = np.random.randn(1)

In [5]:
# 하이퍼파라미터 설정
learning_rate = 0.1
epochs = 1000

In [6]:
# 경사 하강법으로 다층 퍼셉트론 학습
for epoch in range(epochs):
    # 순전파
    z1 = np.dot(X, w1) + b1
    a1 = 1 / (1 + np.exp(-z1))
    z2 = np.dot(a1, w2) + b2
    a2 = 1 / (1 + np.exp(-z2))

    # 오차 계산
    error = y.reshape(-1, 1) - a2

    # 역전파
    delta2 = error * a2 * (1 - a2)
    delta1 = np.dot(delta2, w2.T) * a1 * (1 - a1)

    # 가중치와 편향 업데이트
    w2 += learning_rate * np.dot(a1.T, delta2)
    b2 += learning_rate * np.sum(delta2, axis=0)
    w1 += learning_rate * np.dot(X.T, delta1)
    b1 += learning_rate * np.sum(delta1, axis=0)

In [1]:
import torch
import torch.nn as nn

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Define the model
model = nn.Sequential(
    nn.Linear(2, 2, bias=True),
    nn.Sigmoid(),
    nn.Linear(2, 1, bias=True),
    nn.Sigmoid()
).to(device)

# Define the input and output tensors
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32).to(device)
y = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32).to(device)

# Define the loss function and optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

# Train the model
for epoch in range(5000):
    # Forward pass
    outputs = model(X)
    loss = criterion(outputs, y)

    # Backward and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 1000 == 0:
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, 5000, loss.item()))

# Print the learned weights and biases
print('Learned Weights:')
for name, param in model.named_parameters():
    if 'weight' in name:
        print(name, param.data)
print('Learned Biases:')
for name, param in model.named_parameters():
    if 'bias' in name:
        print(name, param.data)

# Test the model
X_test = torch.tensor([[0.5, 0.5]], dtype=torch.float32).to(device)
with torch.no_grad():
    output = model(X_test)
    prediction = (output >= 0.5).float()

print('Prediction for [0.5, 0.5]:', prediction.item())

X_test = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32).to(device)
with torch.no_grad():
    output = model(X_test)
    prediction = (output >= 0.5).float()

print('Prediction for [[0, 0], [0, 1], [1, 0], [1, 1]]:', prediction.flatten().tolist())


Epoch [1000/5000], Loss: 0.2499
Epoch [2000/5000], Loss: 0.2498
Epoch [3000/5000], Loss: 0.2494
Epoch [4000/5000], Loss: 0.2483
Epoch [5000/5000], Loss: 0.2439
Learned Weights:
0.weight tensor([[-1.1658, -1.2052],
        [ 0.4303, -0.0052]])
2.weight tensor([[-0.9213, -0.3185]])
Learned Biases:
0.bias tensor([-0.2246,  0.0783])
2.bias tensor([0.3911])
Prediction for [0.5, 0.5]: 1.0
Prediction for [[0, 0], [0, 1], [1, 0], [1, 1]]: [0.0, 1.0, 1.0, 1.0]


In [2]:
import torch

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Define the model
model = torch.nn.Sequential(
    torch.nn.Linear(2, 2, bias=True),
    torch.nn.Sigmoid(),
    torch.nn.Linear(2, 1, bias=True),
    torch.nn.Sigmoid()
).to(device)

# Define the input tensors
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]ㅇㅇ], dtype=torch.float32).to(device)
X_test = torch.tensor([0.5, 0.5], dtype=torch.float32).reshape(1, 2).to(device)

# Train the model
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

for epoch in range(5000):
    # Forward pass
    outputs = model(X)
    loss = criterion(outputs, torch.tensor([[0], [1], [1], [0]], dtype=torch.float32).to(device))

    # Backward and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 1000 == 0:
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, 5000, loss.item()))

# Evaluate the model on test input
with torch.no_grad():
    output = model(X_test)
    print('Test input [0.5, 0.5]: {:.4f}'.format(output.item()))

# Print the learned weights and biases
print('Learned Weights:')
for name, param in model.named_parameters():
    if 'weight' in name:
        print(name, param.data)
print('Learned Biases:')
for name, param in model.named_parameters():
    if 'bias' in name:
        print(name, param.data)


Epoch [1000/5000], Loss: 0.2498
Epoch [2000/5000], Loss: 0.2497
Epoch [3000/5000], Loss: 0.2495
Epoch [4000/5000], Loss: 0.2489
Epoch [5000/5000], Loss: 0.2474
Test input [0.5, 0.5]: 0.4965
Learned Weights:
0.weight tensor([[ 0.2074,  0.5127],
        [-0.8927,  0.7664]])
2.weight tensor([[-0.2298,  0.8497]])
Learned Biases:
0.bias tensor([-0.4659, -0.9725])
2.bias tensor([-0.1277])
