In [3]:
import numpy as np
x = np.arange(10)
x.shape = (2,5)
x[-2:10]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
x = np.array([[1., 2.],[np.nan, 3.], [np.nan, np.nan]])
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [13]:
np.isnan(x)

array([[False, False],
       [ True, False],
       [ True,  True]])

In [14]:
~np.isnan(x)

array([[ True,  True],
       [False,  True],
       [False, False]])

In [6]:
x = np.array([1., -1., -2., 3])
x[x<0]

array([-1., -2.])

In [17]:
x = np.arange(35).reshape(5,7)
b = x > 20
x[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [16]:
np.arange(5.)

array([0., 1., 2., 3., 4.])

In [19]:
a = np.ones((1,2,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
np.transpose(a, (1,0,2))

array([[[1., 1., 1.]],

       [[1., 1., 1.]]])